### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by chiral-carbon**
CSV files added

### CODE REVIEW

**Comment by chiral-carbon** [comment]
The categories are as follows:
1. Beaches
2. Temples
3. Dams and Lakes
4. Hill Station
5. Zoos and wildlife sanctuaries
6. Amusement Parks

**Comment by chiral-carbon** [comment]
Added those commits(for categories) as well.

**Review by ayush1999 — CHANGES_REQUESTED** [review]
The `\n`(for newline) doesn't seem to work. Is there any other way of adding a newline inside the column? Or is it like the newline will work once we read it from the c++ file? I'm not sure how reading csv works in c++.

**Comment by ayush1999** [comment]
@chiral-carbon Please check the `\n` symbol. I'm not sure if it should be there (as mentioned in the review). Also, does someone from our group know how to read csv files? I could really use some help. Apparently it isn't as simple as reading csv in python. ;)

**Review by ayush1999 — COMMENTED** [review]
Don't we need a csv file for amusement parks too?

**Comment by chiral-carbon** [comment]
I tried to open the csv file in Excel and tried to add and save newline within a column entry, but that didn't work. So idk yet. Will add when I find out. 
The plan is to look online (duh) and learn how to do file handling in c++. I can help with that. :p

**Comment by chiral-carbon** [comment]
newline problem fixed.

**Comment by chiral-carbon** [comment]
Amusement Parks come under parks.csv

**Comment by ayush1999** [comment]
Merged! :)

**Comment by ayush1999** [comment]
@chiral-carbon Also, any luck reading these CSV files from C++ program?

**Comment by chiral-carbon** [comment]
I found some code that we can use, but I'm still not sure how two read only two columns from the file. Like, in transport, for each option, we should read the place and the transportation mode. 

The method there was to use a counter for the column number, and read for only columns 0 and 2. It used a pos variable to store the delimiter value for each entry, i.e., the comma(' , ') and read substring from beginning of row to first comma for column 0 and and then from second delimiter+1 position to third comma. It used the getline() function to read. 

I'll send the code in a while so that you can see for yourself.

**Comment by ayush1999** [comment]
Sure thing! Btw, we also need to edit and append these CSV files, (as if reading wasn't enough.) ;).

**Comment by chiral-carbon** [comment]
Yes. Never forgot. :p

**Pull request merged**
